version: '3.7'
services:
  nginx:
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile
    
    container_name: nginx_web
    ports:
      - "80:8000"
    volumes:
      - ./static:/static
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./config/backend/Dockerfile
    container_name: backend_web
    working_dir: /app/
    entrypoint:
      - /entrypoint.sh
    volumes:
      - ./static:/static
      - ./static:/app/static
    environment:
      - DJANGO_SETTINGS_MODULE=django_redes_sociales.settings
    expose:
      - "8000"
  frontend:
    build:
      context: .
      dockerfile: ./config/frontend/Dockerfile
    container_name: frontend_web
    working_dir: /app/
    entrypoint:
      - /entrypoint.sh
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./static:/static
    environment:
      - NODE_ENV=development
  redis:
    image: redis:6.0-rc
