version: '3.7'
services:
  nginx:
    image: nginx:1.17
    container_name: nginx_web
    ports:
      - "82:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./media:/usr/share/nginx/html/media/
      - ./static:/static
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./config/backend/Dockerfile
    container_name: backend_web
    working_dir: /app/
    entrypoint:
      - /entrypoint.sh
    volumes:
      - workspace:/backend/app
      - workspace:/media/app/media
      - workspace:/static/app/static
      - workspace:/static/static
      - workspace:/front/app/front
    environment:
      - DJANGO_SETTINGS_MODULE=django_redes_sociales.settings
    expose:
      - "8000"
  frontend:
    build:
      context: .
      dockerfile: ./config/frontend/Dockerfile
    container_name: frontend_web
    working_dir: /app/
    entrypoint:
      - /entrypoint.sh
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - ./media:/media
      - ./static:/static
    environment:
      - NODE_ENV=development
  redis:
    image: redis:6.0-rc
    

volumes:
  workspace:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/jenkins_home/workspace/pipeline_tfg_master/
  
    
 
